# 1. Ingestion Service (API Gateway)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: ai-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
      - name: app
        image: aiops/ingestion-service:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "valkey-redis.data-platform.svc.cluster.local"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.data-platform.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: ai-agents
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: ingestion-service

---
# 2. Triage Service (System-1 Agent)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triage-service
  namespace: ai-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triage-service
  template:
    metadata:
      labels:
        app: triage-service
    spec:
      containers:
      - name: app
        image: aiops/triage-service:v1
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: "postgres.data-platform.svc.cluster.local"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.data-platform.svc.cluster.local:9092"

---
# 3. Analyzer Service (System-2 Agent)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-service
  namespace: ai-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer-service
  template:
    metadata:
      labels:
        app: analyzer-service
    spec:
      containers:
      - name: app
        image: aiops/analyzer-service:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        env:
        - name: OLLAMA_BASE_URL
          value: "http://host.minikube.internal:11434"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.data-platform.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: analyzer-service
  namespace: ai-agents
spec:
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  selector:
    app: analyzer-service
