apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-redis
  namespace: data-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey-redis
  template:
    metadata:
      labels:
        app: valkey-redis
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:7.2-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-redis
  namespace: data-platform
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: valkey-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: data-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "incidents_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: data-platform
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres