---
- name: Add Strimzi Helm repository
  kubernetes.core.helm_repository:
    name: strimzi
    repo_url: "https://strimzi.io/charts/"

- name: Install Strimzi Kafka Operator via Helm
  kubernetes.core.helm:
    name: strimzi-operator
    chart_ref: strimzi/strimzi-kafka-operator
    release_namespace: data-platform
    create_namespace: yes
    values:
      watchNamespaces: ["data-platform"]

- name: Deploy Kafka Cluster and Topics manifests
  kubernetes.core.k8s:
    state: present
    namespace: data-platform
    src: "{{ playbook_dir }}/../k8s/kafka-cluster.yaml"